### ISSUE TITLE
What's up with the licence?

### ISSUE THREAD

**Issue by Maddremor** [Adurnsyl/Adurnsyls-Assorted-Arms-and-Armour#1]
Why on earth did you put up a mod on GitHub with a licence forbidding any modification to the data, which includes forking, contributing and bugfixing? I'm very confused.

**Comment by Adurnsyl** [comment]
So... This is my first project I've actually made public. I thought licenses like that were just a standard when making work public.

**Comment by Adurnsyl** [comment]
So... I'm not a programmer by any stretch of the imagination and this is my first project I've actually made public. I thought licenses like that were just a standard when putting stuff like this up on the internet.

Also sorry about the late reply school has been keeping me extremely busy the past few weeks and I haven't had much time to do anything else.

Edit: if you could message me on discord and help me understand how GitHub works and what I could do better that would be amazing. I'm on the CDDA discord sever as Adurnsyl.
